config/routes.rb
Rails.application.routes.draw do

  resources :locations

  root 'locations#index'

  get 'locations/new/search' => 'locations#search', as: :search

  post 'locations/new/search' => 'locations#find', as: :find

end

app/models/location.rb
class Location < ActiveRecord::Base

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :if => :address_changed?
  after_validation :reverse_geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @location = Location.new
  end

  def create
    edited_params = location_params
    edited_params["address"] = "#{edited_params["address"]}, #{edited_params["city"]}"
    @location = Location.new(edited_params)
    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end

  def show
  end

  def index
  end

  def destroy
    Location.find(params[:id]).destroy
    redirect_to locations_path
  end

  def search
    @search_location = Location.new
    @query
    render :search
  end

  def find
    @search_location = Location.new
    @query = Geocoder.search(params[:location][:address])
  end

  def location_params
    params.require(:location).permit(:address, :city, :latitude, :longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<div>
  <%= form.label :address %>
  <%= form.text_field :address%>
</div>

<div>
  <%= form.label :city %>
  <%= form.text_field :city%>
</div>

<div>
  <%= form.label :latitude %>
  <%= form.text_field :latitude%>
</div>

<div>
  <%= form.label :longitude %>
  <%= form.text_field :longitude%>
</div>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

<%= link_to "Search a location", search_path %><br />
<%= link_to "Create new location", new_location_path %><br />

<% @list = Location.all %>
<% @list.each do |x| %>
  <hr>
  <%= x.address %>
  <%= x.latitude %>
  <%= x.longitude %>
  <%= link_to 'Delete this Location', location_path(x.id), method: :delete, class: "btn btn-default btn-md" %>
  <hr>
<% end %>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>

<h1>New Location</h1>

<%= form_for @location, url: locations_path do |form| %>
  <%= render partial: '/locations/form', object: form %>

  <div class="submit-field">
    <%= form.submit "Create Location"%>
  </div>

<% end %>

<%= link_to "Back to Home page", locations_path %>

app/views/locations/search.html.erb
<h1>Locations#search</h1>
<p>Find me in app/views/locations/search.html.erb</p>

<h1>Location Search</h1>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script>
$(document).ready(function() {
// add double click event
google.maps.event.addListener(Gmaps.map.serviceObject, 'dblclick', function(event) {
    geocodePoint(event.latLng, function(data) {
       console.log(data);
    });
});


function geocodePoint(latlng, callback) {

    var street_number = '';
    var route = '';
    var country = '';
    var postal_code = '';
    var city = '';
    var full_address = '';
    var latitude = latlng.lat();
    var longitude = latlng.lng();

    geocoder.geocode({'latLng': latlng }, function(responses) {

        if (responses &amp;&amp; responses.length &gt; 0) {

              full_address = responses[0].formatted_address;

              responses[0].address_components.forEach(function(el) {
                  el.types.forEach(function(type) {
                      if(type == 'street_number') street_number = el.long_name;
                      if(type == 'route') route = el.long_name;
                      if(type == 'country') country = el.long_name;
                      if(type == 'postal_code') postal_code = el.long_name;
                      if(type == 'locality') city = el.long_name;
                  })
              });
        }
        else {
            alert("Could not geocode... :(");
        }

        callback({
            street_number: street_number,
            route: route,
            postal_code: postal_code,
            city : city,
            country: country,
            latitude: latitude,
            longitude: longitude,
            full_address:full_address
        });
    });
}
});
</script>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>